
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR2 = 18;
  public static final int DOSPUNTOS = 16;
  public static final int PAR1 = 17;
  public static final int CHAR = 14;
  public static final int IGUALACION = 26;
  public static final int IMPRIMIR = 10;
  public static final int ENTERO = 3;
  public static final int XOR = 36;
  public static final int DIFERENTE = 31;
  public static final int DOUBLE = 12;
  public static final int INT = 11;
  public static final int NOT = 35;
  public static final int FINCADENA = 9;
  public static final int AND = 34;
  public static final int MAYORQUE = 28;
  public static final int IGUAL = 32;
  public static final int CARACTER = 6;
  public static final int OR = 33;
  public static final int BOOL = 15;
  public static final int MUTABILIDAD = 8;
  public static final int UMENOS = 21;
  public static final int ID = 7;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int MODULO = 25;
  public static final int MENOS = 20;
  public static final int MENOR = 29;
  public static final int MENORQUE = 27;
  public static final int MAYOR = 30;
  public static final int POTENCIA = 22;
  public static final int BOOLEANO = 5;
  public static final int STRING = 13;
  public static final int DIVISION = 24;
  public static final int MULTIPLICACION = 23;
  public static final int MAS = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "BOOLEANO",
  "CARACTER",
  "ID",
  "MUTABILIDAD",
  "FINCADENA",
  "IMPRIMIR",
  "INT",
  "DOUBLE",
  "STRING",
  "CHAR",
  "BOOL",
  "DOSPUNTOS",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS",
  "POTENCIA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "IGUALACION",
  "MENORQUE",
  "MAYORQUE",
  "MENOR",
  "MAYOR",
  "DIFERENTE",
  "IGUAL",
  "OR",
  "AND",
  "NOT",
  "XOR"
  };
}

