
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR2 = 21;
  public static final int DOSPUNTOS = 16;
  public static final int PAR1 = 20;
  public static final int CHAR = 14;
  public static final int IGUALACION = 31;
  public static final int LLAVE2 = 30;
  public static final int LLAVE1 = 29;
  public static final int IMPRIMIR = 10;
  public static final int ENTERO = 3;
  public static final int XOR = 45;
  public static final int DIFERENTE = 36;
  public static final int DOUBLE = 12;
  public static final int CONTINUE = 47;
  public static final int INT = 11;
  public static final int FOR = 19;
  public static final int MATCH = 50;
  public static final int NOT = 44;
  public static final int AND = 43;
  public static final int FINCADENA = 9;
  public static final int APPEND = 58;
  public static final int IGUAL = 37;
  public static final int MAYORQUE = 33;
  public static final int CARACTER = 6;
  public static final int OR = 42;
  public static final int BOOL = 15;
  public static final int MUTABILIDAD = 8;
  public static final int IF = 17;
  public static final int UMENOS = 24;
  public static final int ID = 7;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int RETURN = 55;
  public static final int STARTWITH = 52;
  public static final int NEW = 56;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int CADENA = 2;
  public static final int MODULO = 28;
  public static final int MENOS = 23;
  public static final int MENOR = 34;
  public static final int CORCHE2 = 54;
  public static final int BREAK = 46;
  public static final int CORCHE1 = 53;
  public static final int VOID = 51;
  public static final int MAYOR = 35;
  public static final int MENORQUE = 32;
  public static final int POTENCIA = 25;
  public static final int BARRABAJA = 39;
  public static final int FLECHA = 38;
  public static final int ELSE = 18;
  public static final int PUNTO = 41;
  public static final int WHILE = 48;
  public static final int LIST = 57;
  public static final int BOOLEANO = 5;
  public static final int STRING = 13;
  public static final int DIVISION = 27;
  public static final int DO = 49;
  public static final int MULTIPLICACION = 26;
  public static final int MAS = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "BOOLEANO",
  "CARACTER",
  "ID",
  "MUTABILIDAD",
  "FINCADENA",
  "IMPRIMIR",
  "INT",
  "DOUBLE",
  "STRING",
  "CHAR",
  "BOOL",
  "DOSPUNTOS",
  "IF",
  "ELSE",
  "FOR",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS",
  "POTENCIA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "LLAVE1",
  "LLAVE2",
  "IGUALACION",
  "MENORQUE",
  "MAYORQUE",
  "MENOR",
  "MAYOR",
  "DIFERENTE",
  "IGUAL",
  "FLECHA",
  "BARRABAJA",
  "COMA",
  "PUNTO",
  "OR",
  "AND",
  "NOT",
  "XOR",
  "BREAK",
  "CONTINUE",
  "WHILE",
  "DO",
  "MATCH",
  "VOID",
  "STARTWITH",
  "CORCHE1",
  "CORCHE2",
  "RETURN",
  "NEW",
  "LIST",
  "APPEND"
  };
}

